function calculateArea (r){
    const pi = Math.PI
    // let π = 3.14
    let area= pi * r**2
    return area
}

console.log (calculateArea(5))
console.log (calculateArea(10))

let reverseString = function(str){ 
    return  str.split('').reverse().join('');
}

console.log (reverseString("hello"))
console.log(reverseString('world')); 


let filterEvenNumbers = (numbers) => {
    re
    // return numbers.filter(number => number % 2 === 0);

};
